watch_stylesheet: true
watch_config: true
debug: false

bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: true 
      acrylic: false 
      dark_mode: true
      round_corners: false
      #border_color: None
    window_flags:
      auto_hide: false
      hide_on_fullscreen: true
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 34
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
        "power_menu",
        "glazewm_workspaces",
        "active_window",
      
        "vscode",
      ##"glazewm_binding_mode"
      ]
      center: [                                                                                                                                                                                                                                                                                                                 
      ##"cava",
        "media"
      ]
      right: [
        "taskbar",
        "clock",
        "wallpapers",
        "wifi",
        "bluetooth",
        "volume",
        "language",
        "systray"
        ]
    layouts:
      left:
        alignment: "left"
        stretch: true
      center:
        alignment: "center"
        stretch: false
      right:
        alignment: "right"
        stretch: true
widgets:
  glazewm_workspaces:
      type: "glazewm.workspaces.GlazewmWorkspacesWidget"
      options:
        offline_label: "GlazeWM Offline"
        hide_empty_workspaces: true
        hide_if_offline: true
        enable_scroll_switching: true
  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "<span>{wifi_icon}</span>"
        label_alt: "{wifi_name}"
        update_interval: 5000
        ethernet_icon: "\uf0ac"
        ethernet_label_alt: "{ip_addr}"
        animation:
          enabled: true
          duration: 200
          type: "fadeInOut"
        menu_config:
          blur: true
          round_corners: true
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
          offset_top: 6
          offset_left: 0
          wifi_icons_secured: [
            "\ue670",
            "\ue671",
            "\ue672",
            "\ue673",
          ]
          wifi_icons_unsecured: [
            "\uec3c",
            "\uec3d",
            "\uec3e",
            "\uec3f",
          ]
        callbacks:
          on_left: "toggle_menu"
          on_middle: "toggle_label"
          on_right: "exec cmd.exe /c start ms-settings:network"
        container_padding:
          top: 0
          left: 
          bottom: 0
          right: 8
        wifi_icons: [
          "\udb82\udd2e",  # Icon for 0% strength
          "\udb82\udd1f",  # Icon for 1-20% strength
          "\udb82\udd22",  # Icon for 21-40% strength
          "\udb82\udd25",  # Icon for 41-80% strength
          "\udb82\udd28"   # Icon for 81-100% strength
        ]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\uf137"
      label_expanded: "\uf138"
      label_position: "right" # Can be "left" or "right"
      icon_size: 15 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      #show_unpinned: false
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      unpinned_vis_btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "<span>\uf11c</span>{lang[country_code]}"
      update_interval: 1
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "exec cmd.exe /c start ms-settings:keyboard"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 8
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 15
      max_length_ellipsis: "..."
      monitor_exclusive: false 
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 6
        bottom: 0
        right: 8
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      max_field_size:
        label: 17
        label_alt: 24
      show_thumbnail: true
      controls_only: false
      controls_left: true
      hide_empty: false
      thumbnail_alpha: 255
      thumbnail_padding: 0
      thumbnail_edge_fade: true
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      scrolling_label:
        enabled: true
        update_interval_ms: 30
        style: "left"  # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 1
      # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 60
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 27
        max_artist_size: 60
        show_source: true
      media_menu_icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      callbacks:
        on_left: "toggle_play_pause"
        on_middle: "toggle_label"
        on_right: "toggle_media_menu"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M %d.%m.%y}"
      label_alt: "{%H:%M %d.%m.%y}"
      animation:
        enabled: false
      callbacks:
        on_left: "toggle_calendar"
      calendar: 
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "None"
        alignment: "center"
        direction: "down"
        distance: 6
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      update_interval: 600
      hide_decimal: true
      location: "Russia Saint-Petersburg"
      callbacks:
        on_left: "toggle_card"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\U0001F319"
        cloudyDay: "\U00002601"
        cloudyNight: "\U0001F315"
        rainyDay: "\U0001F327"
        rainyNight: "\U0001F327\U0001F311"
        snowyIcyDay: "\U00002744"
        snowyIcyNight: "\U0001F328"
        blizzardDay: "\U0001F32C"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      weather_card: 
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "None"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 64
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{volume}"
      tooltip: false
      animation:
        enabled: true
        duration: 200
        type: "fadeInOut"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_volume_menu"
        on_middle: "exec cmd.exe /c start ms-settings:apps-volume"
        on_right: "exec cmd.exe /c start ms-settings:sound"
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        distance: 6
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\u23fc"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        signout: ["\udb80\udf43", "Sign out"]
        cancel: ["", "Cancel"]
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
        duration: 100
        type: "fadeInOut"
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      callbacks:
        on_left: "toggle_window"
        on_middle: "close_app"
        on_right: "do_nothing"
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{device_name}"
      icons:
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\admin\\pictures\\wallpapers" # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
          enabled: true
          blur: true
          image_width: 200
          image_per_page: 6
          show_buttons: true
          orientation: "portrait"
          image_spacing: 4
          lazy_load: true
          lazy_load_delay: 80
          lazy_load_fadein: 400
          image_corner_radius: 20
          enable_cache: true
  vscode:
    type: "yasb.vscode.VSCodeWidget"
    options:
      label: "<span>\udb82\ude1e</span>"
      label_alt: "<span>\udb82\ude1e</span> recents"
      menu_title: "<span style='font-weight:bold'>VScode</span> recents"
      max_field_size: 50
      folder_icon: "\uf114"
      file_icon: "\uf016"
      truncate_to_root_dir: false
      state_storage_path: D:\scoop\apps\vscode\current\data\user-data\User\globalStorage\state.vscdb
      hide_folder_icon: false
      hide_file_icon: false
      max_number_of_folders: 30
      max_number_of_files: 30 # set to 0 if you only want folders
      modified_date_format: "Date modified: %Y-%m-%d %H:%M"
      cli_command: "code" # or "codium" or "windsurf" or any other CLI command to open the workspace
      menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        alignment: 'center'
        offset_top: 0
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 2
      reverse: 0
      sensitivity: 100
      foreground: "#89b4fa"
      gradient_color_1: '#74c7ec'
      gradient_color_2: '#89b4fa'
      gradient_color_3: '#cba6f7'
      bars_number: 8
      bar_spacing: 2
      bar_width: 4
      sleep_timer: 0
      hide_empty: false
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0